site_name: Roll Off Club
site_description: 'Everything you need to know about Roll Off in Fall Guys'
site_author: 'Alex Lockwood'
site_url: 'https://rolloff.club'

repo_name: 'roll-off-club'
repo_url: 'https://github.com/alexjlockwood/roll-off-club'
remote_branch: gh-pages
edit_uri: edit/main/docs/

nav:
  - 'Home': index.md
  - 'Getting Started':
    - getting-started/index.md
    - getting-started/learning-the-rolls.md
    - getting-started/blue-spins-faster-than-orange.md
    - getting-started/reducing-desync.md
    - getting-started/avoiding-griefers.md
  - 'Rolls':
    - rolls/index.md
    - rolls/easy-4.md
    - rolls/isolated-duo.md
    - rolls/closed-open-open-closed.md
    - rolls/pillar-trench.md
    - rolls/5-waller.md
    - rolls/grand-canyon.md
  - 'Variations':
    - variations/index.md
    - 'Hardest Variations':
      - variations/5-waller-grand-canyon.md
      - variations/5-waller-open-closed.md
      - variations/closed-open-grand-canyon.md
      - variations/closed-open-open-closed.md
      - variations/isolated-duo-grand-canyon.md
    - 'Hard Variations':
      - variations/5-waller-easy-4.md
      - variations/5-waller-isolated-duo.md
      - variations/5-waller-pillar-trench.md
      - variations/easy-4-grand-canyon.md
      - variations/easy-4-open-closed.md
    - 'Medium Variations':
      - variations/closed-open-easy-4.md
      - variations/closed-open-isolated-duo.md
      - variations/closed-open-pillar-trench.md
      - variations/easy-4-pillar-trench.md
      - variations/isolated-duo-isolated-duo.md
    - 'Easy Variations':
      - variations/easy-4-easy-4.md
      - variations/easy-4-isolated-duo.md
      - variations/isolated-duo-easy-4.md
      - variations/isolated-duo-open-closed.md
      - variations/isolated-duo-pillar-trench.md
  - 'Advanced':
    - advanced/index.md
    - advanced/counting-laps.md
    - advanced/isolated-duo-god-jumps.md
    - advanced/no-jump-dive-timeouts.md
    - advanced/recognizing-variations.md
    - advanced/wall-jumps-one-rolling.md
  - glossary.md

theme:
  name: 'material'
  custom_dir: overrides
  language: 'en'
  palette:
    - media: "(prefers-color-scheme)"
      primary: 'deep orange'
      accent: 'blue'
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'deep orange'
      accent: 'blue'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'blue'
      toggle:
        icon: material/brightness-4
        name: Switch to system theme
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'
  features:
    - navigation.tabs
    - navigation.indexes 
    - navigation.footer
    - content.action.edit

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.betterem
  - pymdownx.superfences

plugins:
  - search
  - redirects:
      redirect_maps:
        advanced/recognizing-variations-early.md: advanced/recognizing-variations.md
  - minify:
      minify_html: true
  - i18n:
      default_language: en
      docs_structure: suffix
      languages:
        en:
          name: English
          build: true
          site_name: "Roll Off Club"
        ko:
          name: 한국어 (Korean)
          build: true
          site_name: "Roll Off 클럽"
        zh:
          name: TODO (Chinese)
          build: true
          site_name: "TODO"
      nav_translations:
        ko:
          Home: 홈
          Getting Started: 시작하기
          Rolls: 패턴
          Variations: 변형
          Hardest Variations: 최고난도 변형
          Hard Variations: 고난도 변형
          Medium Variations: 중간 난도 변형
          Easy Variations: 쉬운 난도 변형
          Advanced: 고급
          Glossary: 용어집
        zh:
          Home: TODO
          Getting Started: TODO
          Rolls: TODO
          Variations: TODO
          Hardest Variations: TODO
          Hard Variations: TODO
          Medium Variations: TODO
          Easy Variations: TODO
          Advanced: TODO
          Glossary: TODO

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xf9D89Hfxa
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/alexjlockwood
  analytics:
    provider: google
    property: G-NHXDMJB5FJ
  generator: false

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2022-2023 Alex Lockwood
